import type { Locale } from "./content";

export const guideCopy = {
  tr: {
    name: "Sahada bugün",
    short: "Adana Open",
    openCta: "Aç",
    tagline: "Adana Open WTA 125 · maç programı, bilet ve saha bilgisi.",
    install: "Ana ekrana ekle",
    installHint: "Paylaş menüsünden Ana Ekrana Ekle’yi seçin.",
    site: "adanaopen.com",
    now: "Şimdi",
    matches: "Maçlar",
    events: "Etkinlikler",
    news: "Duyuru",
    live: "Canlı",
    info: "Saha",
    sss: "SSS",
    players: "Oyuncular",
    phaseUpcoming: "Turnuvaya kalan süre",
    phaseLive: "Turnuva devam ediyor",
    phaseEnded: "Turnuva sona erdi",
    today: "Bugün",
    next: "Sıradaki gün",
    firstBall: "İlk top",
    timeSoon: "Saatler duyurulacak",
    courtsOn: "kort",
    matchesCount: "maç",
    seeAll: "Tümü",
    pinned: "Sabit",
    latest: "Son duyurular",
    quick: "Hızlı erişim",
    streamSoon: "Canlı yayın henüz başlamadı",
    streamLive: "Canlı yayını izle",
    streamHint: "Yayın bağlantısı hazır olduğunda bu sayfada ve Instagram’da paylaşılır.",
    officialScores: "WTA resmi skorlar",
    scoreboard: "Kort panosu",
    scoreboardEmpty: "Skorlar maçlar başladığında burada yer alır.",
    results: "Sonuçlar",
    cancelled: "Oynanmadı",
    retired: "Çekildi",
    onCourt: "Kortta",
    upNext: "Sırada",
    complete: "Bitti",
    warmup: "Isınma",
    serving: "Servis",
    draftNote:
      "Çekişmeler ve skorlar WTA resmi programından alınır. Kort ve saat süpervizör kararıyla değişebilir.",
    followedBy: "Ardından",
    notBefore: "En erken",
    afterRest: "Dinlenme sonrası",
    toFinish: "Yarım kaldı",
    wildcard: "WC",
    filterAll: "Tümü",
    filterMatch: "Maç",
    filterMusic: "Müzik",
    filterEvent: "Etkinlik",
    noEvents: "Bu kategoride etkinlik bulunmuyor.",
    faq: "Sık sorulan sorular",
    contact: "İletişim",
    share: "Paylaş",
    shared: "Bağlantı kopyalandı",
    searchPlayers: "Oyuncu ara",
    noPlayers: "Aramanızla eşleşen oyuncu bulunamadı.",
    wtaProfile: "WTA",
    maps: "Yol tarifi",
    call: "Ara",
    email: "E-posta",
    instagram: "Instagram",
    tickets: "Biletler",
    ticketBuy: "Bilet al",
    ticketHint: "Biletix ve kulüp satış noktalarında",
    ticketSub: "Biletix",
    social: "Sosyal",
    practical: "Saha bilgisi",
    addHome: "Ana ekrana ekle",
    streamOffline: "Canlı yayın turnuva haftasında bu sayfada açılır.",
    streamEnded: "Yayın sona erdi.",
    watchInstagram: "Instagram’da takip et",
    updated: "Güncelleme",
    legendQual: "Eleme",
    legendSingles: "Tekler",
    legendDoubles: "Çiftler",
    mainDraw: "Ana tablo",
    mainDrawNote: "Tekler son 32 çekişmeleri. Skorlar maç programında güncellenir.",
    emptyNews: "Şu anda yeni duyuru yok.",
    heroKicker: "WTA 125 · ATDSK",
    heroEyebrow: "26 Eylül – 4 Ekim",
    heroTitleUpcoming: "Eleme maçları başlıyor",
    heroTitleLive: "Maçlar devam ediyor",
    heroTitleEnded: "Turnuva sona erdi",
    nextMatch: "Sıradaki maç",
    upcomingMatches: "Yaklaşan maçlar",
    onCourtNow: "Şu an kortta",
    todayMatches: "Bugünün maçları",
    playDone: "Bugünün maçları tamamlandı",
    todayOnSite: "Bugün sahada",
    alwaysOn: "Sahada her gün",
    sponsors: "Sponsorlar",
    notifyTitle: "Bildirimler",
    notifyBody: "Maç saatleri ve duyurular telefonunuza gönderilir.",
    notifyEnable: "Bildirimlere izin ver",
    notifyOn: "Bildirimler açık",
    notifyDenied: "Tarayıcı bildirimleri kapalı. İzni tarayıcı ayarlarından açabilirsiniz.",
    notifyNeedHttps: "Bildirimler için siteyi HTTPS üzerinden veya ana ekrandan açın.",
    notifyError: "Bildirim kaydı tamamlanamadı. Lütfen daha sonra yeniden deneyin.",
    sendTitle: "Bildirim gönder",
    sendBody: "Bildirimleri açmış telefonlara maç veya duyuru iletisi gönderin.",
    sendHow:
      "Ziyaretçi ana sayfada «Bildirimlere izin ver»e basar. Siz buradan başlık ve metin yazıp gönderirsiniz. Bildirime basılınca seçtiğiniz sayfa açılır.",
    sendPassword: "Yönetici şifresi",
    sendHeadline: "Başlık",
    sendMessage: "Metin",
    sendLink: "Açılacak sayfa",
    sendCta: "Gönder",
    sendOk: "Bildirim gönderildi",
    sendFail: "Gönderilemedi. Şifreyi kontrol edin.",
    sendCount: "kayıtlı cihaz",
    sendPresetMatch: "Maç",
    sendPresetNews: "Duyuru",
    contestTitle: "Adana Open Tahmin Yarışması",
    contestLead:
      "Turnuvaya dair tahminlerini paylaş. Doğru veya en yakın tahminleri yapanlar arasındaki çekilişle toplam 20 kişiye sürpriz hediye verilecek. Ödüller değişkenlik gösterebilir.",
    contestCta: "Tahmin et, kazan",
    contestOpenForm: "Yarışmaya katıl",
    contestDeadline: "Son katılım: 4 Ekim 2026, 10:00",
    contestClosed:
      "Adana Open Tahmin Yarışması’na katılım sona ermiştir. İlginiz için teşekkür ederiz. Kazananları öğrenmek için bizi takip etmeye devam edin!",
    contestSuccess:
      "Katılımın başarıyla alındı! Adana Open final gününde açıklanacak sonuçlar için bizi takip etmeyi unutma. Bol şans!",
    contestSubmit: "Tahminlerimi gönder",
    contestFirst: "Ad",
    contestLast: "Soyad",
    contestPhone: "Cep telefonu",
    contestPhoneHint: "05xx xxx xx xx",
    contestQ1: "Sizce turnuva boyunca toplam kaç ace atılacak?",
    contestQ2: "Sizce turnuvadaki tamamlanan tüm maçların toplam süresi yaklaşık kaç dakika olacak?",
    contestQ2Hint: "Resmî maç sürelerinin toplamını dakika olarak tahmin ediniz.",
    contestQ3: "Sizce final maçı kaç dakika sürecek?",
    contestQ3Hint: "Final maçının resmî süresini dakika olarak tahmin ediniz.",
    contestKvkk: "KVKK Aydınlatma Metni’ni okudum ve bilgilendirildim.",
    contestRiza:
      "Yarışmaya katılım kapsamında kişisel verilerimin belirtilen amaçlarla işlenmesine ilişkin Açık Rıza Metni’ni okudum ve onaylıyorum.",
    contestRules: "Yarışma Katılım Koşulları’nı ve Çekiliş Kuralları’nı okudum, kabul ediyorum.",
    contestMarketing: "Kampanya, etkinlik ve duyurular hakkında telefon/SMS yoluyla ticari ileti almak istiyorum.",
    contestLinkKvkk: "KVKK Aydınlatma Metni",
    contestLinkRiza: "Açık Rıza Metni",
    contestLinkRules: "Yarışma Katılım Koşulları",
    contestLinkDraw: "Çekiliş Kuralları",
    contestLinkMarketing: "Ticari ileti metni",
    contestErrName: "Ad ve soyadı yazın.",
    contestErrPhone: "Geçerli bir Türkiye cep telefonu girin.",
    contestErrGuess: "Tahminler yalnızca pozitif tam sayı olabilir.",
    contestErrConsent: "Zorunlu onayları işaretleyin.",
    contestErrDup: "Bu telefon numarasıyla daha önce katılım yapılmış.",
    contestErrClosed: "Katılım süresi doldu.",
    contestErrLimit: "Çok fazla deneme. Lütfen biraz sonra yeniden deneyin.",
    contestErrGeneric: "Katılım kaydedilemedi. Lütfen yeniden deneyin.",
    contestDays: "gün",
    contestHours: "saat",
    contestMinutes: "dk",
    contestSeconds: "sn",
    contestClose: "Kapat",
    contestDraftNote: "Metinler hukuk danışmanı onayı için yönetim panelinden düzenlenebilir.",
    contestOptional: "İsteğe bağlı",
    contestRequired: "Zorunlu",
    contestContact: "İletişim",
    contestLegalTitle: "Yasal metinler",
    sendPresetLive: "Canlı yayın",
  },
  en: {
    name: "Today on site",
    short: "Adana Open",
    openCta: "Open",
    tagline: "Adana Open WTA 125 · match schedule, tickets and venue information.",
    install: "Add to Home Screen",
    installHint: "Open Share and choose Add to Home Screen.",
    site: "adanaopen.com",
    now: "Now",
    matches: "Matches",
    events: "Events",
    news: "News",
    live: "Live",
    info: "Venue",
    sss: "FAQ",
    players: "Players",
    phaseUpcoming: "Time until the tournament",
    phaseLive: "The tournament is under way",
    phaseEnded: "The tournament has ended",
    today: "Today",
    next: "Next day",
    firstBall: "First ball",
    timeSoon: "Times to be announced",
    courtsOn: "courts",
    matchesCount: "matches",
    seeAll: "See all",
    pinned: "Pinned",
    latest: "Latest news",
    quick: "Quick links",
    streamSoon: "The livestream has not started yet",
    streamLive: "Watch live",
    streamHint: "The stream link will be published here and on Instagram when it is ready.",
    officialScores: "Official WTA scores",
    scoreboard: "Court board",
    scoreboardEmpty: "Scores will appear here once play begins.",
    results: "Results",
    cancelled: "Not played",
    retired: "Retired",
    onCourt: "On court",
    upNext: "Next",
    complete: "Finished",
    warmup: "Warm-up",
    serving: "Serving",
    draftNote:
      "Draws and scores come from the official WTA order of play. Courts and times may change.",
    followedBy: "Followed by",
    notBefore: "Not before",
    afterRest: "After rest",
    toFinish: "To finish",
    wildcard: "WC",
    filterAll: "All",
    filterMatch: "Match",
    filterMusic: "Music",
    filterEvent: "Event",
    noEvents: "There are no events in this category.",
    faq: "Frequently asked questions",
    contact: "Contact",
    share: "Share",
    shared: "Link copied",
    searchPlayers: "Search players",
    noPlayers: "No players match your search.",
    wtaProfile: "WTA",
    maps: "Directions",
    call: "Call",
    email: "Email",
    instagram: "Instagram",
    tickets: "Tickets",
    ticketBuy: "Buy tickets",
    ticketHint: "On sale at Biletix and at the club",
    ticketSub: "Biletix",
    social: "Social",
    practical: "Venue information",
    addHome: "Add to Home Screen",
    streamOffline: "The livestream will open here during tournament week.",
    streamEnded: "The stream has ended.",
    watchInstagram: "Follow on Instagram",
    updated: "Updated",
    legendQual: "Qualifying",
    legendSingles: "Singles",
    legendDoubles: "Doubles",
    mainDraw: "Main draw",
    mainDrawNote: "Singles round of 32. Scores update on the order of play.",
    emptyNews: "There are no new announcements.",
    heroKicker: "WTA 125 · ATDSK",
    heroEyebrow: "26 Sep – 4 Oct",
    heroTitleUpcoming: "Qualifying begins",
    heroTitleLive: "Play continues",
    heroTitleEnded: "The tournament has ended",
    nextMatch: "Next match",
    upcomingMatches: "Upcoming matches",
    onCourtNow: "On court now",
    todayMatches: "Today’s matches",
    playDone: "Today’s matches are finished",
    todayOnSite: "Today on site",
    alwaysOn: "Throughout the tournament",
    sponsors: "Sponsors",
    notifyTitle: "Notifications",
    notifyBody: "Match times and announcements are sent to your phone.",
    notifyEnable: "Allow notifications",
    notifyOn: "Notifications are on",
    notifyDenied: "Browser notifications are blocked. You can allow them in your browser settings.",
    notifyNeedHttps: "Open the site over HTTPS or from your Home Screen to receive notifications.",
    notifyError: "This device could not be registered. Please try again later.",
    sendTitle: "Send a notification",
    sendBody: "Send a match or news alert to phones that have opted in.",
    sendHow:
      "Visitors tap «Allow notifications» on the home screen. You write a title and message here. Tapping the alert opens the page you choose.",
    sendPassword: "Admin password",
    sendHeadline: "Title",
    sendMessage: "Message",
    sendLink: "Open URL",
    sendCta: "Send",
    sendOk: "Notification sent",
    sendFail: "Could not send. Check the password.",
    sendCount: "subscribed devices",
    sendPresetMatch: "Match",
    sendPresetNews: "News",
    contestTitle: "Adana Open Prediction Contest",
    contestLead:
      "Share your tournament predictions. A raffle among the closest guesses will send surprise gifts to 20 people. Prizes may vary.",
    contestCta: "Predict and win",
    contestOpenForm: "Enter the contest",
    contestDeadline: "Entries close: 4 October 2026, 10:00",
    contestClosed:
      "Entries for the Adana Open Prediction Contest have closed. Thank you. Follow us for the winners.",
    contestSuccess:
      "Your entry is in. Watch for the results on Adana Open final day. Good luck!",
    contestSubmit: "Send my predictions",
    contestFirst: "First name",
    contestLast: "Last name",
    contestPhone: "Mobile number",
    contestPhoneHint: "05xx xxx xx xx",
    contestQ1: "How many aces will be served in the tournament?",
    contestQ2: "About how many minutes will all completed matches last in total?",
    contestQ2Hint: "Estimate the combined official match durations in minutes.",
    contestQ3: "How many minutes will the final last?",
    contestQ3Hint: "Estimate the official duration of the final in minutes.",
    contestKvkk: "I have read the privacy notice and have been informed.",
    contestRiza: "I have read and accept the explicit consent text for processing my data for this contest.",
    contestRules: "I have read and accept the Entry terms and Raffle rules.",
    contestMarketing: "I would like to receive campaign, event and news messages by phone/SMS.",
    contestLinkKvkk: "Privacy notice",
    contestLinkRiza: "Explicit consent",
    contestLinkRules: "Entry terms",
    contestLinkDraw: "Raffle rules",
    contestLinkMarketing: "Marketing consent",
    contestErrName: "Enter your first and last name.",
    contestErrPhone: "Enter a valid Turkish mobile number.",
    contestErrGuess: "Predictions must be positive whole numbers.",
    contestErrConsent: "Please tick the required consents.",
    contestErrDup: "This mobile number has already been used.",
    contestErrClosed: "The contest is closed.",
    contestErrLimit: "Too many attempts. Please try again shortly.",
    contestErrGeneric: "The entry could not be saved. Please try again.",
    contestDays: "days",
    contestHours: "hrs",
    contestMinutes: "min",
    contestSeconds: "sec",
    contestClose: "Close",
    contestDraftNote: "These texts can be edited in the admin panel for legal review.",
    contestOptional: "Optional",
    contestRequired: "Required",
    contestContact: "Contact",
    contestLegalTitle: "Legal texts",
    sendPresetLive: "Livestream",
  },
} as const;

export type GuideMessages = (typeof guideCopy)[Locale];

export function gCopy(locale: Locale): GuideMessages {
  return guideCopy[locale];
}
