import type { Locale } from "./content";

export const guideCopy = {
  tr: {
    name: "Sahada bugün",
    short: "Adana Open",
    openCta: "Aç",
    tagline: "Maç, etkinlik, yayın ve saha — tek yerde.",
    install: "Ana ekrana ekle",
    installHint: "Paylaş → Ana Ekrana Ekle. Turnuva cebinizde kalsın.",
    site: "Siteye dön",
    now: "Şimdi",
    matches: "Maçlar",
    events: "Etkinlikler",
    news: "Duyuru",
    live: "Canlı",
    info: "Saha",
    players: "Oyuncular",
    phaseUpcoming: "Kalan süre",
    phaseLive: "Turnuva devam ediyor",
    phaseEnded: "Turnuva sona erdi",
    today: "Bugün",
    next: "Sıradaki gün",
    firstBall: "İlk top",
    timeSoon: "Yakında belli olacak",
    courtsOn: "kort",
    matchesCount: "maç",
    seeAll: "Tümü",
    pinned: "Sabit",
    latest: "Son duyurular",
    quick: "Hızlı erişim",
    streamSoon: "Canlı yayın yakında",
    streamLive: "Canlı yayını aç",
    streamHint: "Resmi link netleşince burada ve Instagram’da görünecek.",
    officialScores: "WTA resmi skor",
    scoreboard: "Kort panosu",
    scoreboardEmpty: "Canlı skor henüz yok. Kort sırası taslak plana göredir.",
    onCourt: "Kortta",
    upNext: "Sırada",
    complete: "Bitti",
    warmup: "Isınma",
    serving: "Servis",
    draftNote: "Şu anki plan budur; saatler değişebilir. Eleme ilk top 10:30. Pazartesi’den ana tablo yakında. Günceli bu siteden takip edin.",
    followedBy: "Ardından",
    filterAll: "Tümü",
    filterMatch: "Maç",
    filterMusic: "Müzik",
    filterEvent: "Etkinlik",
    noEvents: "Bu filtrede etkinlik yok.",
    faq: "Sık sorulanlar",
    contact: "İletişim",
    share: "Paylaş",
    shared: "Kopyalandı",
    searchPlayers: "Oyuncu ara",
    noPlayers: "Eşleşen oyuncu yok.",
    wtaProfile: "WTA",
    maps: "Yol tarifi",
    call: "Ara",
    email: "E-posta",
    instagram: "Instagram",
    tickets: "Biletler",
    ticketBuy: "Bilet al",
    ticketHint: "Biletix ve kulüpte satışta",
    ticketSub: "Adana Open WTA 125",
    social: "Sosyal",
    practical: "Saha bilgisi",
    addHome: "Uygulama gibi kullan",
    streamOffline: "Yayın henüz başlamadı.",
    streamEnded: "Yayın sona erdi.",
    watchInstagram: "Instagram’da takip et",
    updated: "Güncelleme",
    legendQual: "Eleme",
    legendSingles: "Tekler",
    legendDoubles: "Çiftler",
    emptyNews: "Yeni duyuru yok.",
    heroKicker: "WTA 125 · ATDSK",
    heroEyebrow: "26 Eylül – 4 Ekim",
    heroTitleUpcoming: "Hazır mısın?",
    heroTitleLive: "Sahadasınız.",
    heroTitleEnded: "Teşekkürler Adana.",
    nextMatch: "Sıradaki maç",
    upcomingMatches: "Yaklaşan maçlar",
    onCourtNow: "Şu an kortta",
    todayOnSite: "Bugün sahada",
    alwaysOn: "Sahada her gün",
    sponsors: "Sponsorlar",
    notifyTitle: "Bildirimler",
    notifyBody:
      "Maç saati, skor ve duyuru telefonunuza gelir. Bir kez izin verin — uygulama indirmeye gerek yok.",
    notifyEnable: "Bildirim izni ver",
    notifyOn: "Bildirimler açık",
    notifyDenied: "Tarayıcı bildirimi kapalı. Ayarlardan izin verin.",
    notifyNeedHttps: "Bildirim için siteyi HTTPS üzerinden veya ana ekrandan açın.",
    notifyError: "Bildirim kaydı alınamadı. Daha sonra tekrar deneyin.",
    sendTitle: "Bildirim gönder",
    sendBody: "Bildirimleri açmış telefonlara maç veya duyuru yollayın.",
    sendHow:
      "Ziyaretçi ana sayfada «Bildirim izni ver» der. Siz buradan başlık ve metin yazıp gönderirsiniz. Bildirime basınca seçtiğiniz sayfa açılır.",
    sendPassword: "Yönetici şifresi",
    sendHeadline: "Başlık",
    sendMessage: "Metin",
    sendLink: "Açılacak sayfa",
    sendCta: "Gönder",
    sendOk: "Bildirim gönderildi",
    sendFail: "Gönderilemedi. Şifreyi kontrol edin.",
    sendCount: "kayıtlı cihaz",
    sendPresetMatch: "Maç",
    sendPresetNews: "Duyuru",
    sendPresetLive: "Canlı yayın",
  },
  en: {
    name: "Today on site",
    short: "Adana Open",
    openCta: "Open",
    tagline: "Matches, events, stream and venue — in one place.",
    install: "Add to Home Screen",
    installHint: "Share → Add to Home Screen. Keep the tournament in your pocket.",
    site: "Back to site",
    now: "Now",
    matches: "Matches",
    events: "Events",
    news: "News",
    live: "Live",
    info: "Venue",
    players: "Players",
    phaseUpcoming: "Starts in",
    phaseLive: "Tournament in progress",
    phaseEnded: "The tournament has ended",
    today: "Today",
    next: "Next day",
    firstBall: "First ball",
    timeSoon: "Times to be confirmed",
    courtsOn: "courts",
    matchesCount: "matches",
    seeAll: "See all",
    pinned: "Pinned",
    latest: "Latest news",
    quick: "Quick links",
    streamSoon: "Livestream coming soon",
    streamLive: "Watch live",
    streamHint: "The official link will appear here and on Instagram.",
    officialScores: "Official WTA scores",
    scoreboard: "Court board",
    scoreboardEmpty: "No live scores yet. Court order follows the draft plan.",
    onCourt: "On court",
    upNext: "Next",
    complete: "Finished",
    warmup: "Warm-up",
    serving: "Serving",
    draftNote: "This is the current plan; times can shift. Qualifying first ball 10:30. From Monday, main-draw times soon. Follow this site for updates.",
    followedBy: "Followed by",
    filterAll: "All",
    filterMatch: "Match",
    filterMusic: "Music",
    filterEvent: "Event",
    noEvents: "Nothing in this filter.",
    faq: "FAQ",
    contact: "Contact",
    share: "Share",
    shared: "Copied",
    searchPlayers: "Search players",
    noPlayers: "No matching players.",
    wtaProfile: "WTA",
    maps: "Directions",
    call: "Call",
    email: "Email",
    instagram: "Instagram",
    tickets: "Tickets",
    ticketBuy: "Buy tickets",
    ticketHint: "On sale at Biletix and on site",
    ticketSub: "Adana Open WTA 125",
    social: "Social",
    practical: "Venue info",
    addHome: "Use like an app",
    streamOffline: "The stream has not started yet.",
    streamEnded: "The stream has ended.",
    watchInstagram: "Follow on Instagram",
    updated: "Updated",
    legendQual: "Qualifying",
    legendSingles: "Singles",
    legendDoubles: "Doubles",
    emptyNews: "No news yet.",
    heroKicker: "WTA 125 · ATDSK",
    heroEyebrow: "26 Sep – 4 Oct",
    heroTitleUpcoming: "Are you ready?",
    heroTitleLive: "You’re on site.",
    heroTitleEnded: "Thank you, Adana.",
    nextMatch: "Next match",
    upcomingMatches: "Upcoming matches",
    onCourtNow: "On court now",
    todayOnSite: "Today on site",
    alwaysOn: "All tournament",
    sponsors: "Sponsors",
    notifyTitle: "Notifications",
    notifyBody:
      "Match times, scores and announcements come to your phone. Allow once — no app to download.",
    notifyEnable: "Allow notifications",
    notifyOn: "Alerts on",
    notifyDenied: "Notifications are blocked. Allow them in browser settings.",
    notifyNeedHttps: "Open the site on HTTPS or from your Home Screen for alerts.",
    notifyError: "Could not save this device. Try again later.",
    sendTitle: "Send a notification",
    sendBody: "Push a match or announcement alert to phones that opted in.",
    sendHow:
      "Visitors tap «Allow notifications» on the home screen. You write a title and message here. Tapping the alert opens the page you choose.",
    sendPassword: "Admin password",
    sendHeadline: "Title",
    sendMessage: "Message",
    sendLink: "Open URL",
    sendCta: "Send",
    sendOk: "Notification sent",
    sendFail: "Could not send. Check the password.",
    sendCount: "subscribed devices",
    sendPresetMatch: "Match",
    sendPresetNews: "News",
    sendPresetLive: "Livestream",
  },
} as const;

export type GuideMessages = (typeof guideCopy)[Locale];

export function gCopy(locale: Locale): GuideMessages {
  return guideCopy[locale];
}
